### ISSUE TITLE
Proto API definitions should not use gogoproto

### ISSUE THREAD

**Issue by mandarjog** [istio/api#107] opened 2017-05-25 22:05 UTC
Mixer API definitions use language and implementation specific `gogoproto` options.

Mixer server implementation details are therefore leaked onto the API surface.

While generating code in other supported languages these options are at best **irrelevant** or worst, they make it difficult to compile.

We should not use language specific options in the published proto spec.
The language and implementation specific options should reside with the server implementation.

**Comment by mandarjog** [comment] 2017-05-25 22:09
@costinm @qiwzhang

**Comment by kyessenov** [comment] 2017-05-25 22:13
These are just proto options, and do not affect the standard protoc go plugin. Although I agree that we should use standard go plugin.

**Comment by mandarjog** [comment] 2017-05-25 22:17
It does not affect the generated code, however if you are generating `C++` code, you still need to have these gogo option definitions available.

**Comment by qiwzhang** [comment] 2017-05-25 22:33
Yes,  the bazel rule to compile these proto files for c++ will need to include gogo package, and add a dependency for it.

https://github.com/istio/mixerclient/blob/master/repositories.bzl#L498

and

https://github.com/istio/mixerclient/blob/master/repositories.bzl#L551

**Comment by costinm** [comment] 2017-05-26 15:19
The problem is that an API should not impose a dependency on particular
implementation - in particular
a language-specific one. It's fine for mixer to use gogo as implementation
- but shouldn't leak into the API
definition.

There is another implementation-leaking issue - the use of map<> may be
convenient for mixer server
implementation or for the api bindings, but as we discovered it has a cost
it imposes on the proxy
(or anyone making requests). The key hash randomization was a big problem -
but even with it
fixed, the runtime cost of a map ( memory, computation ) is higher than for
a repeated field.
The map may guarantee uniqueness of the key - but there are other ways to
do this.

**Comment by qiwzhang** [comment] 2017-05-26 17:19
Raised https://github.com/istio/api/issues/108 to replace map with repeated field.

**Comment by geeknoid** [comment] 2018-01-10 22:07
I don't think we care about this. Can we close this issue?

**Comment by kyessenov** [comment] 2018-03-21 16:19
Annotations are not part of the data protocol for protobufs, so I think there is no issue with extra-annotations in the proto files. Bazel and build concerns are irrelevant.

**Closed by kyessenov** 2018-03-21 16:19 UTC
