### ISSUE TITLE
Consolidate proxy and mixer config

### ISSUE THREAD

**Issue by ZackButcher** [istio/api#74] opened 2017-04-12 22:12 UTC
We haven't made an effort to ensure that mixer and proxy configurations have a similar look-and-feel. We need to go over both config schemas and ensure they use common language in comments, similar field names for similar concepts, similar style (e.g. the mixer uses descriptor objects throughout, does the proxy?), etc.

I don't think this needs to be done pre-alpha, but it almost certainly is needed pre-beta. The earlier the better since config changes will be breaking for our users.

**Comment by geeknoid** [comment] 2017-04-12 23:17
Duplicate of issue #31

**Closed by geeknoid** 2017-04-12 23:17 UTC
Labels: enhancement
