### ISSUE TITLE
Proposal for refactoring mixerclient configuration

### ISSUE THREAD

**Issue by ayj** [istio/api#344] opened 2018-02-01 23:02 UTC
The current mixerclient protos conflates user intent with implementation specific filter config. We ought to decouple them. User facing config is dimensioned by feature (auth, quota, api-spec) and should be organized according to the [proposed proto package scheme](https://docs.google.com/document/d/1C_NMYj9ZhdUWwZMWUoX_SLU8VoiV8U8V6yUJVYcdSS8/edit#heading=h.qex63c29z2to). Filter config is dimensioned by service (i.e. envoy route).

This will allow better independent evolution of the user-facing APIs from filter/proxy specific implementations, e.g. mixerclient, upstream envoy ([auth](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/auth/auth.proto), [ratelimit](https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/ratelimit/ratelimit.proto)).

We should also refactor the mixerclient filter configuration to be defined per route (via RDS) instead of per listener (via LDS). This is both more performant, as service config can then be delivered via RDS instead of the more costly LDS, which requires draining listeners, and more consistent with upstream Envoy filters, e.g. [here](https://github.com/envoyproxy/data-plane-api/blob/a07a36853e698d5fee7b011d7abd1dcb87eda45e/envoy/api/v2/route/route.proto#L98).

- [x] Introduce a new user-facing AuthenticationPolicy. @diemtvu already started this work (see https://github.com/istio/api/pull/335). Pilot consumes AuthenticationPolicy and produce the corresponding mtls/auth filter configuration for envoy/mixerclient.

- [ ] Introduce a new user-facing API proto. OpenAPI (v2/v3), gRPC, and generic REST schemes should be considered. Options include a single umbrella type with subtypes per scheme or first-class types for each of the scheme. Pilot consumes these API spec(s) and produces the corresponding normalized [HTTPAPISpec](https://github.com/istio/api/blob/master/mixer/v1/config/client/api_spec.proto) for mixerclient filter.

- [ ] Introduce a new user-facing Quota proto. Schema is TBD. Config WG probably has useful input on what this should look like. Pilot consums this new proto and produce corresponding [QuotaSpec](https://github.com/istio/api/blob/master/mixer/v1/config/client/quota.proto) for mixerclient filter.

- [ ] Binding/Scoping API is only needed for user facing APIs. [QuotaSpecBinding](https://github.com/istio/api/blob/a31ac6dbd68579a553367ebb20b1c2b4551404bf/mixer/v1/config/client/quota.proto#L122), [HTTPAPISpecBinding](https://github.com/istio/api/blob/a31ac6dbd68579a553367ebb20b1c2b4551404bf/mixer/v1/config/client/api_spec.proto#L217), and [EndUserAuthenticationPolicySpecBinding](https://github.com/istio/api/blob/a31ac6dbd68579a553367ebb20b1c2b4551404bf/mixer/v1/config/client/auth.proto#L165) should be removed. Equivalent bindings should be created for the user-facing auth, quota, and api-spec definitions. It would be great if there were some consistency with [RouteRule](https://github.com/istio/api/blob/a31ac6dbd68579a553367ebb20b1c2b4551404bf/routing/v1alpha2/route_rule.proto#L119)'s concepts/terminology when possible. For example, it seems reasonable to bind an API spec to service name (i.e. host) and/or entry point to the mesh (i.e. ingress/gateway).

- [x] Refactor [mixer/v1/config/client/client_config.proto](https://github.com/istio/api/blob/master/mixer/v1/config/client/client_config.proto) so that per-service configuration can be provided via RDS.

**Comment by mandarjog** [comment] 2018-02-02 00:01
As part of adding mixer calls on egress and external services, I am stuffing serviceconfig as it exists today into per route as b64, in addition to where it is today.
The service config should only be present for `inbound|*` listener filters so it is not torn down that often, so the problem is not as bad for the current use case.

However since I am adding mixer calls  for egress / external service it will result in listener reload when a new external service is added, so I am doing the expedient thing of moving it to per route opaque config as is, and still use V1 api.

The other changes on the list are orthogonal.

**Comment by mandarjog** [comment] 2018-02-02 00:02
One issue right now, is that filter config is unnecessarily being populated in unrelated listeners, so I am actually fixing that too.

**Comment by mandarjog** [comment] 2018-02-02 00:07
```yaml
      opaque_config:
              destination.service: httpbin.default.svc.cluster.local
              mixer_check: 'on'
              mixer_forward: 'off'
              mixer_report: 'on'
              per_route_config: base64(json(per_route_config))
             per_route_config_sha: sha(base64(json(per_route_config)))
```

**Comment by ayj** [comment] 2018-02-02 00:38
service-config per route is more important for shared proxies (e.g. ingress) and less critical for sidecar proxies. Providing both per-listen and per-route b64 encoded works shorter term, but we should eventually switch over to per-route only. Maybe v2 api is a good time?

**Comment by mandarjog** [comment] 2018-02-02 00:58
I have been thinking of that. Just start with V2 for RDS (REST), but then would we rather move to a templatized model?

**Comment by ayj** [comment] 2018-02-02 01:12
The data object over which the template is applied may need some refactoring when we switch from per-listener to per-route. I think there may be other ongoing pilot config/api refactoring that effects this area. I guess we can get the proxy/mixerclient side working as intended and deal with pilot refactoring independently.

**Closed** 2018-10-26 21:52 UTC
Labels: area/policies and telemetry, kind/enhancement
