### ISSUE TITLE
Serialization issue

### ISSUE THREAD

**Issue by mnestero** [istio/api#1178] opened 2019-11-22 08:05 UTC
**Bug description**
When serializing DestinationRule with TrafficPolicy.Tls.Mode = TLSSettings_DISABLE getting empty TLSmode object, all the constants works as expected.
spec:
  host: example.net
  trafficPolicy:
    tls: {}

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Expected to get:
spec:
  host: example.net
  trafficPolicy:
    tls: DISABLE
**Steps to reproduce the bug**
Creating new DestinationRule object
ns := &v1alpha3.DestinationRule{
		ObjectMeta: v1.ObjectMeta{
			Name:                       "test",
		},
		Spec:       networkingv1alpha3.DestinationRule{
			Host:                 "example.net",
			TrafficPolicy:        &networkingv1alpha3.TrafficPolicy{
				Tls:     &networkingv1alpha3.TLSSettings{
					Mode:     networkingv1alpha3.TLSSettings_DISABLE,
				},
			},
		},
	}
e := json.NewSerializerWithOptions(json.DefaultMetaFactory, nil, nil, json.SerializerOptions{Yaml: true})
err = e.Encode(ns, os.Stdout)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

	istio.io/api v0.0.0-20191120195622-f0abe0c81e59
	istio.io/client-go v0.0.0-20191120150049-26c62a04cdbc // indirect
**How was Istio installed?**
go get istio.io/client-go@1.4
**Environment where bug was observed (cloud vendor, OS, etc)**
Mac OS 10.14.6

**Comment by mnestero** [comment] 2020-01-16 07:32
Looks like the apimachinery serializer treats TLSSettings_TLSmode = 0 as default integer and just omit serializing that field.

**Comment by howardjohn** [comment] 2020-11-18 17:57
This is a duplicate of https://github.com/istio/api/issues/1616. thanks

**Closed by howardjohn** 2020-11-18 17:57 UTC
Labels: lifecycle/needs-triage
